const cardArray = [
    { name: "fruit1", img: "images\fruit1.jpg" },
    { name: "fruit2", img: "images\fruit2.jpg" },
    { name: "fruit3", img: "images\fruit3.jpg" },
    { name: "fruit4", img: "images\fruit4.jpg" },
    { name: "fruit5", img: "images\fruit5.jpg" },
    { name: "fruit6", img: "images\fruit6.jpg" },
    { name: "fruit7", img: "images\fruit7.jpg" },
    { name: "fruit8", img: "images\fruit8.jpg" },
    { name: "fruit9", img: "images\fruit9.jpg" },
    { name: "fruit10", img: "images\fruit10.jpg" },
    { name: "fruit11", img: "images\fruit11.jpg" },
    { name: "fruit12", img: "images\fruit12.jpg" },
    { name: "fruit13", img: "images\fruit13.jpg" },
    { name: "fruit14", img: "images\fruit14.jpg" },
    { name: "fruit15", img: "images\fruit15.jpg" },
    { name: "fruit16", img: "images\fruit16.jpg" },
    { name: "fruit17", img: "images\fruit17.jpg" },
    { name: "fruit18", img: "images\fruit18.jpg" },
    { name: "fruit19", img: "images\fruit19.jpg" },
    { name: "fruit20", img: "images\fruit20.jpg" },
    { name: "fruit21", img: "images\fruit21.jpg" },
    { name: "fruit22", img: "images\fruit22.jpg" },
    { name: "fruit23", img: "images\fruit23.jpg" },
    { name: "fruit24", img: "images\fruit24.jpg" },
    { name: "fruit25", img: "images\fruit25.jpg" },

]

